# Generated by Django 2.2.16 on 2021-05-04 13:04

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import jsonfield.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    replaces = [('daard_database', '0001_initial'), ('daard_database', '0002_auto_20210325_0808'), ('daard_database', '0003_auto_20210325_0821'), ('daard_database', '0004_auto_20210325_0840'), ('daard_database', '0005_auto_20210325_0841'), ('daard_database', '0006_auto_20210325_1251'), ('daard_database', '0007_diseaselibrary_technic'), ('daard_database', '0008_diseaselibrary_bone_change'), ('daard_database', '0009_auto_20210329_0752'), ('daard_database', '0010_auto_20210329_0753'), ('daard_database', '0011_formconfig'), ('daard_database', '0012_auto_20210329_0835'), ('daard_database', '0013_auto_20210329_0837'), ('daard_database', '0014_auto_20210329_0903'), ('daard_database', '0015_auto_20210329_0930'), ('daard_database', '0016_auto_20210329_0935'), ('daard_database', '0017_diseaselibrary_proxy'), ('daard_database', '0018_remove_diseaselibrary_proxy'), ('daard_database', '0019_auto_20210330_0903'), ('daard_database', '0020_auto_20210330_0908'), ('daard_database', '0021_auto_20210330_0917'), ('daard_database', '0022_auto_20210330_0917'), ('daard_database', '0023_auto_20210330_0922'), ('daard_database', '0024_auto_20210330_0925'), ('daard_database', '0025_auto_20210330_1049'), ('daard_database', '0026_auto_20210330_1050'), ('daard_database', '0027_auto_20210330_1051'), ('daard_database', '0028_auto_20210330_1111'), ('daard_database', '0029_technic_c'), ('daard_database', '0030_auto_20210330_1314'), ('daard_database', '0031_diseasecase'), ('daard_database', '0032_auto_20210331_1238'), ('daard_database', '0033_diseasecase_bone'), ('daard_database', '0034_auto_20210331_1244'), ('daard_database', '0035_remove_diseasecase_archaeological_site_suggestion'), ('daard_database', '0036_auto_20210331_1249'), ('daard_database', '0037_auto_20210331_1251'), ('daard_database', '0038_auto_20210407_1145'), ('daard_database', '0039_auto_20210407_1231'), ('daard_database', '0040_auto_20210408_1620'), ('daard_database', '0041_bonerelation'), ('daard_database', '0042_diseaselibrary_age_class'), ('daard_database', '0043_remove_diseaselibrary_age_class'), ('daard_database', '0044_bone_section'), ('daard_database', '0045_auto_20210504_0718'), ('daard_database', '0046_diseasecase_bone_inventory'), ('daard_database', '0047_auto_20210504_0727'), ('daard_database', '0048_auto_20210504_0733'), ('daard_database', '0049_auto_20210504_0734'), ('daard_database', '0050_diseasecase_origin'), ('daard_database', '0051_auto_20210504_0741'), ('daard_database', '0052_auto_20210504_0749')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(default=0, editable=False)),
                ('lft', models.PositiveIntegerField(default=0, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='daard_database.bone')),
                ('rght', models.PositiveIntegerField(default=0, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('section', models.CharField(choices=[('cranial_district', 'Cranial district'), ('axial_skeleton', 'Axial skeleton'), ('right_upper_limb', 'Right upper limb'), ('left_upper_limb', 'Left upper limb'), ('right_lower_limb', 'Right lower limb'), ('left_lower_limb', 'Left lower limb')], default='cranial_district', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BoneChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adults', models.BooleanField(blank=True, default=False)),
                ('subadults', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BoneChangeBoneProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technic_proxy', to='daard_database.technic')),
                ('bone', mptt.fields.TreeManyToManyField(related_name='bone_proxy', to='daard_database.Bone')),
                ('bone_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bone_change_proxy', to='daard_database.bonechange')),
                ('anomalies', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='daard_database.diseaselibrary')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_class', models.CharField(choices=[('Foetus', 'Foetus'), ('0–3', '0 – 3'), ('4–6', '4 – 6'), ('7–12', '7 – 12'), ('13–20', '13 – 20'), ('21–35', '21 – 35'), ('36–50', '36 – 50'), ('50+', '50 +'), ('Unknown', 'Unknown')], max_length=200)),
                ('contact_email', models.EmailField(default='toni.schoenbuchner@csgis.de', max_length=400)),
                ('contact_institut', models.CharField(default='a', max_length=400)),
                ('age', models.CharField(choices=[('unknown', 'Unknown'), ('does_not_apply', 'Does not apply')], default='unknown', max_length=200)),
                ('age_freetext', models.CharField(blank=True, max_length=200)),
                ('archaeological_burial_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('multiple', 'Multiple'), ('unknown', 'UNKNOWN')], max_length=400)),
                ('archaeological_funery_context', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('unknown', 'UNKNOWN')], default='unknown', max_length=400)),
                ('archaeological_individualid', models.CharField(default='1', max_length=400)),
                ('archaeological_site', models.CharField(default='k', max_length=400)),
                ('archaeological_tombid', models.CharField(default='1', max_length=400)),
                ('chronology', models.CharField(default='f', max_length=400)),
                ('chronology_freetext', models.CharField(blank=True, max_length=400)),
                ('reference_images', models.CharField(max_length=600)),
                ('contact_firstname', models.CharField(default='toni', max_length=400)),
                ('contact_lastname', models.CharField(default='schönbuchner', max_length=400)),
                ('dating_method', models.CharField(choices=[('human_bone', 'Human bone'), ('animal_bone', 'Animal bone'), ('horn', 'Horn'), ('ivory', 'Ivory'), ('tooth', 'Tooth'), ('hair', 'Hair'), ('skin', 'Skin'), ('soft_tissues', 'Soft tissues'), ('wood', 'Wood'), ('textile', 'Textile'), ('botanical_remains', 'Botanical remains'), ('stratigraphic', 'Stratigraphic'), ('funerary-structures', 'Funerary structures'), ('grave_goods', 'Grave goods'), ('archives', 'Archives'), ('texts', 'Texts'), ('epigraphic_sources', 'Epigraphic sources'), ('numismatic', 'Numismatic')], default='skin', max_length=400)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies_case', to='daard_database.diseaselibrary')),
                ('dna_analyses', models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful'), ('absent', 'Absent'), ('unknown', 'UNKNOWN')], default='unknown', max_length=400)),
                ('dna_analyses_link', models.CharField(default='f', max_length=400)),
                ('publication', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], default='a', max_length=400)),
                ('sex', models.CharField(choices=[('f', 'F'), ('f?', 'F?'), ('unknown', 'UNKNOWN'), ('m', 'M'), ('m?', 'M?')], default='m', max_length=200)),
                ('storage_condition', models.CharField(choices=[('exhibition', 'Exhibition'), ('accessible_for_study', 'Accessible for study'), ('not_accessible_for_study', 'Not accessible for study'), ('does_not_apply', 'Does not apply'), ('unknown', 'UNKNOWN')], default='unknown', max_length=400)),
                ('storage_place', models.CharField(choices=[('institution_1', 'Institution 1'), ('institution_2', 'Institution 2'), ('institution_3', 'Institution 3'), ('unknown', 'UNKNOWN')], default='unknown', max_length=400)),
                ('storage_place_freetext', models.CharField(default='f', max_length=400)),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('geoserver_id', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('is_approved', models.BooleanField(default=False)),
                ('adults', models.BooleanField(default=False)),
                ('subadults', models.BooleanField(default=False)),
                ('inventory', jsonfield.fields.JSONField(default={})),
                ('bone_relations', jsonfield.fields.JSONField(default={})),
                ('origin', models.CharField(default='', max_length=400)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BoneRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomalies_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies_case', to='daard_database.diseasecase')),
                ('bone_case', mptt.fields.TreeManyToManyField(related_name='bone_proxy_case', to='daard_database.Bone')),
                ('bone_change_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bone_change_proxy_case', to='daard_database.bonechange')),
                ('technic_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technic_proxy_case', to='daard_database.technic')),
            ],
        ),
    ]
