# Generated by Django 2.2.16 on 2021-05-06 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daard_database', '0001_squashed_0052_auto_20210504_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daard_case_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bone',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bone',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bone',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bone',
            name='section',
            field=models.CharField(choices=[('cranial_district', 'Cranial district'), ('axial_skeleton', 'Axial skeleton'), ('right_upper_limb', 'Right upper limb'), ('left_upper_limb', 'Left upper limb'), ('right_lower_limb', 'Right lower limb'), ('left_lower_limb', 'Left lower limb')], max_length=255),
        ),
        migrations.AlterField(
            model_name='bone',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='bonechangeboneproxy',
            name='anomalies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='daard_database.DiseaseLibrary'),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='age',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('does_not_apply', 'Does not apply')], max_length=200),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_funery_context',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('unknown', 'UNKNOWN')], max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_individualid',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_site',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_tombid',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='bone_relations',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='chronology',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='contact_email',
            field=models.EmailField(max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='contact_firstname',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='contact_institut',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='contact_lastname',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='dating_method',
            field=models.CharField(choices=[('human_bone', 'Human bone'), ('animal_bone', 'Animal bone'), ('horn', 'Horn'), ('ivory', 'Ivory'), ('tooth', 'Tooth'), ('hair', 'Hair'), ('skin', 'Skin'), ('soft_tissues', 'Soft tissues'), ('wood', 'Wood'), ('textile', 'Textile'), ('botanical_remains', 'Botanical remains'), ('stratigraphic', 'Stratigraphic'), ('funerary-structures', 'Funerary structures'), ('grave_goods', 'Grave goods'), ('archives', 'Archives'), ('texts', 'Texts'), ('epigraphic_sources', 'Epigraphic sources'), ('numismatic', 'Numismatic')], max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='dna_analyses',
            field=models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful'), ('absent', 'Absent'), ('unknown', 'UNKNOWN')], max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='dna_analyses_link',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='inventory',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='origin',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='publication',
            field=models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='sex',
            field=models.CharField(choices=[('f', 'F'), ('f?', 'F?'), ('unknown', 'UNKNOWN'), ('m', 'M'), ('m?', 'M?')], max_length=200),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='storage_condition',
            field=models.CharField(choices=[('exhibition', 'Exhibition'), ('accessible_for_study', 'Accessible for study'), ('not_accessible_for_study', 'Not accessible for study'), ('does_not_apply', 'Does not apply'), ('unknown', 'UNKNOWN')], max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='storage_place',
            field=models.CharField(choices=[('institution_1', 'Institution 1'), ('institution_2', 'Institution 2'), ('institution_3', 'Institution 3'), ('unknown', 'UNKNOWN')], max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='storage_place_freetext',
            field=models.CharField(max_length=400),
        ),
    ]
