# Generated by Django 2.2.16 on 2021-05-06 14:40

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0001_squashed_0004_auto_20210506_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
