# Generated by Django 3.1.7 on 2021-03-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disease',
            new_name='DiseaseLibrary',
        ),
    ]
