# Generated by Django 2.2.16 on 2021-05-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0002_auto_20210506_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasecase',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='diseasecase',
            name='contact_firstname',
        ),
        migrations.RemoveField(
            model_name='diseasecase',
            name='contact_institut',
        ),
        migrations.RemoveField(
            model_name='diseasecase',
            name='contact_lastname',
        ),
    ]
