# Generated by Django 3.1.7 on 2021-03-25 08:40

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0003_auto_20210325_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonechangeboneproxy',
            name='bone',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daard_database.bone'),
        ),
    ]
