# Generated by Django 3.1.7 on 2021-03-25 08:41

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0004_auto_20210325_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonechangeboneproxy',
            name='bone',
        ),
        migrations.AddField(
            model_name='bonechangeboneproxy',
            name='bone',
            field=mptt.fields.TreeManyToManyField(to='daard_database.Bone'),
        ),
    ]
