# Generated by Django 3.1.7 on 2021-03-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0006_auto_20210325_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaselibrary',
            name='technic',
            field=models.ManyToManyField(through='daard_database.BoneChangeBoneProxy', to='daard_database.Technic'),
        ),
    ]
