# Generated by Django 3.1.7 on 2021-03-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0008_diseaselibrary_bone_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaselibrary',
            name='adults',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='diseaselibrary',
            name='subadults',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
