# Generated by Django 3.1.7 on 2021-03-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0009_auto_20210329_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaselibrary',
            name='adults',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='diseaselibrary',
            name='subadults',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
