# Generated by Django 2.2.20 on 2021-11-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0011_auto_20210927_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_burial_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('multiple', 'Multiple'), ('unknown', 'UNKNOWN')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_funery_context',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('unknown', 'UNKNOWN')], max_length=400, null=True),
        ),
    ]
root@6abbb57b6a79:/usr/src/dai_geonode# /usr/src/daard-database/daard_database/migrations/0012_auto_20211116_1351.py
bash: /usr/src/daard-database/daard_database/migrations/0012_auto_20211116_1351.py: Permission denied
root@6abbb57b6a79:/usr/src/dai_geonode# cat /usr/src/daard-database/daard_database/migrations/0012_auto_20211116_1351.py
# Generated by Django 2.2.20 on 2021-11-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0011_auto_20210927_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_burial_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('multiple', 'Multiple'), ('unknown', 'UNKNOWN')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_funery_context',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('unknown', 'UNKNOWN')], max_length=400, null=True),
        ),
    ]
