# Generated by Django 3.1.7 on 2021-03-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0011_formconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formconfig',
            old_name='config',
            new_name='values',
        ),
    ]
