# Generated by Django 3.1.7 on 2021-03-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0013_auto_20210329_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formconfig',
            name='config',
            field=models.TextField(blank=True, null=True, serialize=False),
        ),
    ]
