# Generated by Django 3.1.7 on 2021-03-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0014_auto_20210329_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formconfig',
            old_name='name',
            new_name='formular',
        ),
        migrations.RenameField(
            model_name='formconfig',
            old_name='config',
            new_name='values',
        ),
    ]
