# Generated by Django 3.1.7 on 2021-03-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0015_auto_20210329_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formconfig',
            old_name='formular',
            new_name='form',
        ),
    ]
