# Generated by Django 3.1.7 on 2021-03-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0017_diseaselibrary_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaselibrary',
            name='proxy',
        ),
    ]
