# Generated by Django 3.1.7 on 2021-03-30 09:03

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0018_remove_diseaselibrary_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonechangeboneproxy',
            name='Disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_proxy', to='daard_database.diseaselibrary'),
        ),
        migrations.AlterField(
            model_name='bonechangeboneproxy',
            name='bone',
            field=mptt.fields.TreeManyToManyField(related_name='bone_proxy', to='daard_database.Bone'),
        ),
        migrations.AlterField(
            model_name='bonechangeboneproxy',
            name='bone_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bone_change_proxy', to='daard_database.bonechange'),
        ),
        migrations.AlterField(
            model_name='bonechangeboneproxy',
            name='technic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technic_proxy', to='daard_database.technic'),
        ),
    ]
