# Generated by Django 3.1.7 on 2021-03-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0019_auto_20210330_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonechangeboneproxy',
            old_name='Disease',
            new_name='disease',
        ),
    ]
