# Generated by Django 3.1.7 on 2021-03-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0021_auto_20210330_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaselibrary',
            name='bone_change',
            field=models.ManyToManyField(to='daard_database.BoneChange'),
        ),
        migrations.AddField(
            model_name='diseaselibrary',
            name='technic',
            field=models.ManyToManyField(to='daard_database.Technic'),
        ),
    ]
