# Generated by Django 3.1.7 on 2021-03-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0023_auto_20210330_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonechangeboneproxy',
            old_name='disease',
            new_name='disease_library',
        ),
    ]
