# Generated by Django 3.1.7 on 2021-03-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0024_auto_20210330_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonechangeboneproxy',
            old_name='disease_library',
            new_name='diseaselibrary',
        ),
    ]
