# Generated by Django 3.1.7 on 2021-03-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0025_auto_20210330_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonechangeboneproxy',
            name='diseaselibrary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseaselibrary_proxy', to='daard_database.diseaselibrary'),
        ),
    ]
