# Generated by Django 2.2.20 on 2022-02-02 16:59

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0025_auto_20220202_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='storage_place',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
