# Generated by Django 3.1.7 on 2021-03-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0026_auto_20210330_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonechangeboneproxy',
            name='diseaselibrary',
        ),
        migrations.AddField(
            model_name='bonechangeboneproxy',
            name='disease_library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disease_library_proxy', to='daard_database.diseaselibrary'),
            preserve_default=False,
        ),
    ]
