# Generated by Django 3.1.7 on 2021-03-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0027_auto_20210330_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonechangeboneproxy',
            name='disease_library',
        ),
        migrations.AddField(
            model_name='bonechangeboneproxy',
            name='anomalies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='daard_database.diseaselibrary'),
            preserve_default=False,
        ),
    ]
