# Generated by Django 3.1.7 on 2021-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0028_auto_20210330_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='technic',
            name='c',
            field=models.CharField(blank=True, choices=[('UN', 'Unpublished'), ('PB', 'Published')], max_length=200, null=True),
        ),
    ]
