# Generated by Django 3.1.7 on 2021-03-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0029_technic_c'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormConfig',
        ),
        migrations.RemoveField(
            model_name='technic',
            name='c',
        ),
    ]
