# Generated by Django 3.1.7 on 2021-03-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0030_auto_20210330_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('age_class', models.CharField(choices=[('Foetus', 'Foetus'), ('0–3', '0 – 3'), ('4–6', '4 – 6'), ('7–12', '7 – 12'), ('13–20', '13 – 20'), ('21–35', '21 – 35'), ('36–50', '36 – 50'), ('50+', '50 +'), ('Unknown', 'Unknown')], max_length=200)),
            ],
        ),
    ]
