# Generated by Django 3.1.7 on 2021-03-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0031_diseasecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='CONTACT_EMAIL',
            field=models.EmailField(default='toni.schoenbuchner@csgis.de', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='CONTACT_INSTITUT',
            field=models.CharField(default='a', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='age',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('does_not_apply', 'Does not apply')], default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='age_freetext',
            field=models.CharField(choices=[], default='f', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='archaeological_burial_type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple'), ('unknown', 'UNKNOWN')], default='unknown', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='archaeological_funery_context',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('unknown', 'UNKNOWN')], default='unknown', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='archaeological_individualid',
            field=models.CharField(default='1', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='archaeological_site',
            field=models.CharField(default='k', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='archaeological_site_suggestion',
            field=models.CharField(default='k', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='archaeological_tombid',
            field=models.CharField(default='1', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='bone_bx',
            field=models.CharField(choices=[('>75%', '>75%'), ('<75%', '<75%'), ('absent', 'ABSENT'), ('unknown', 'UNKNOWN')], default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='bone_by',
            field=models.CharField(choices=[('>75%', '>75%'), ('<75%', '<75%'), ('absent', 'ABSENT'), ('unknown', 'UNKNOWN')], default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='bone_bz',
            field=models.CharField(choices=[('>75%', '>75%'), ('<75%', '<75%'), ('absent', 'ABSENT'), ('unknown', 'UNKNOWN')], default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='chronology',
            field=models.CharField(default='f', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='chronology_freetext',
            field=models.CharField(default='f', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='collection_link',
            field=models.CharField(default='f', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='contact_firstname',
            field=models.CharField(default='toni', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='contact_lastname',
            field=models.CharField(default='schönbuchner', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='dating_method',
            field=models.CharField(choices=[('human_bone', 'Human bone'), ('animal_bone', 'Animal bone'), ('horn', 'Horn'), ('ivory', 'Ivory'), ('tooth', 'Tooth'), ('hair', 'Hair'), ('skin', 'Skin'), ('soft_tissues', 'Soft tissues'), ('wood', 'Wood'), ('textile', 'Textile'), ('botanical_remains', 'Botanical remains'), ('stratigraphic', 'Stratigraphic'), ('funerary-structures', 'Funerary structures'), ('grave_goods', 'Grave goods'), ('archives', 'Archives'), ('texts', 'Texts'), ('epigraphic_sources', 'Epigraphic sources'), ('numismatic', 'Numismatic')], default='skin', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='disease',
            field=models.CharField(default='Dwarf', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='dna_analyses',
            field=models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful'), ('absent', 'Absent'), ('unknown', 'UNKNOWN')], default='unknown', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='dna_analyses_freetext',
            field=models.CharField(default='f', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='publication',
            field=models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], default='a', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='publication_freetext',
            field=models.CharField(default='f', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='sex',
            field=models.CharField(choices=[('f', 'F'), ('f?', 'F?'), ('unknown', 'UNKNOWN'), ('m', 'M'), ('m?', 'M?')], default='m', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='storage_condition',
            field=models.CharField(choices=[('exhibition', 'Exhibition'), ('accessible_for_study', 'Accessible for study'), ('not_accessible_for_study', 'Not accessible for study'), ('does_not_apply', 'Does not apply'), ('unknown', 'UNKNOWN')], default='unknown', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='storage_place',
            field=models.CharField(choices=[('institution_1', 'Institution 1'), ('institution_2', 'Institution 2'), ('institution_3', 'Institution 3'), ('unknown', 'UNKNOWN')], default='unknown', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='storage_place_freetext',
            field=models.CharField(default='f', max_length=400),
            preserve_default=False,
        ),
    ]
