# Generated by Django 3.1.7 on 2021-03-31 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0032_auto_20210331_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='bone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daard_database.bone'),
        ),
    ]
