# Generated by Django 3.1.7 on 2021-03-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0034_auto_20210331_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasecase',
            name='archaeological_site_suggestion',
        ),
    ]
