# Generated by Django 3.1.7 on 2021-03-31 12:49

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0035_remove_diseasecase_archaeological_site_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasecase',
            old_name='CONTACT_EMAIL',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='diseasecase',
            old_name='CONTACT_INSTITUT',
            new_name='contact_institut',
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='uuid',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
