# Generated by Django 3.1.7 on 2021-03-31 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0036_auto_20210331_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasecase',
            name='uuid',
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='geoserver_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
