# Generated by Django 3.1.7 on 2021-04-07 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0037_auto_20210331_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='geoserver_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
