# Generated by Django 3.1.7 on 2021-04-07 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0038_auto_20210407_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='age_freetext',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='chronology_freetext',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='geoserver_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
