# Generated by Django 3.1.7 on 2021-04-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0042_diseaselibrary_age_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaselibrary',
            name='age_class',
        ),
    ]
