# Generated by Django 3.1.7 on 2021-04-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0043_remove_diseaselibrary_age_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='bone',
            name='section',
            field=models.CharField(choices=[('cranial_district', 'Cranial district'), ('axial_skeleton', 'Axial skeleton'), ('right_upper_limb', 'Right upper limb'), ('left_upper_limb', 'Left upper limb'), ('right_lower_limb', 'Right lower limb'), ('left_lower_limb', 'Left lower limb')], default='cranial_district', max_length=255),
            preserve_default=False,
        ),
    ]
