# Generated by Django 3.1.7 on 2021-05-04 07:18

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0044_bone_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='adults',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='subadults',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bone',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='daard_database.bone'),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_burial_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('multiple', 'Multiple'), ('unknown', 'UNKNOWN')], max_length=400),
        ),
    ]
