# Generated by Django 3.1.7 on 2021-05-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0047_auto_20210504_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasecase',
            old_name='collection_link',
            new_name='reference_images',
        ),
    ]
