# Generated by Django 3.1.7 on 2021-05-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0048_auto_20210504_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='reference_images',
            field=models.CharField(max_length=600),
        ),
    ]
