# Generated by Django 3.1.7 on 2021-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0049_auto_20210504_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='origin',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
