# Generated by Django 3.1.7 on 2021-05-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0050_diseasecase_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasecase',
            old_name='dna_analyses_freetext',
            new_name='dna_analyses_link',
        ),
        migrations.RemoveField(
            model_name='diseasecase',
            name='publication_freetext',
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
