# Generated by Django 3.1.7 on 2021-05-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0051_auto_20210504_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasecase',
            old_name='bone_inventory',
            new_name='inventory',
        ),
    ]
